### ISSUE TITLE
Memory leak while running the game

### ISSUE THREAD

**Issue by hmyeh** [NilsHullegien/TempleRunGroup5#15]

**Comment by levilime** [comment]
Very big problem! Probably through the implementation of texture loading in Rungame line 63 : {{{batch.draw(new Texture(obj.getTexture()), obj.getX(), obj.getY());}}} which uses a FileHandle. It should be implemented instead like this: Load the textures at the start of the game in the global Batch, the batch passed around through the screens, so that they only need to load once.

**Comment by mwolting** [comment]
Fixed in pull request #3

**Comment by levilime** [comment]
Big problem indeed resolved in #3, there is still a leak, but way smaller. I think it would be better if the textures were just loaded at the start of the program as described above, why would we otherwise send the batch parameter to the Gamerunner?
